CREATE TABLE USUARIO_CPF (
ID_USUARIO INT NOT NULL,
ID_CPF INT NOT NULL,
NOME varchar(100),
DATA_DE_NASCIMENTO INT,
NOME_DO_PAI varchar (100),
NOME_DA_MAE varchar (100),
PRIMARY KEY (ID_USUARIO, ID_CPF)
);