DROP DATABASE IF EXISTS DBEXERCICIO10;
CREATE DATABASE DBEXERCICIO10;
USE DBEXERCICIO10;
CREATE TABLE ARTESA (
	IDARTESA INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(45),
    EMAIL VARCHAR(45),
    SEXO CHAR(1),
    SENHA VARCHAR(45),
    CELULAR VARCHAR (15),
    RUA VARCHAR (150),
    NUMERO INT,
    BAIRRO VARCHAR (45),
    CEP VARCHAR (8),
    CIDADE VARCHAR (45),
    ESTADO CHAR(2),
	PRIMARY KEY (IDARTESA)
);