DROP DATABASE IF EXISTS DBEXERCICIO10;
CREATE DATABASE DBEXERCICIO10;
USE DBEXERCICIO10;
CREATE TABLE PRODUTO (
	IDPRODUTO INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(45),
    DESCRICAO VARCHAR (150),
    TIPO ENUM ('REDE', 'TAPETE'),
    VALOR NUMERIC (8,2),
	PRIMARY KEY (IDPRODUTO)
);