DROP DATABASE IF EXISTS exercicio14;
CREATE DATABASE exercicio14;
USE exercicio14;

-- CRIANDO AS TABELAS
CREATE TABLE USUARIO (
	IDUSUARIO INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(100)
    , LOGIN VARCHAR(100)
    , SENHA VARCHAR (100)
    , DATA_CADASTRO INT
    , PRIMARY KEY (IDUSUARIO)
);

CREATE TABLE VIDEO (
	IDVIDEO INT NOT NULL AUTO_INCREMENT
	, TITULO VARCHAR (100)
    , CATEGORIA VARCHAR (100)
    , DATA_PUBLICACAO INT
    , PRIMARY KEY (IDVIDEO)
);

CREATE TABLE ACESSAR (
	IDUSUARIO INT NOT NULL
    , IDVIDEO INT NOT NULL
    , PRIMARY KEY (IDUSUARIO, IDVIDEO)
    , FOREIGN KEY (IDUSUARIO) REFERENCES PEDIDO(IDUSUARIO)
    , FOREIGN KEY (IDVIDEO) REFERENCES PRODUTO(IDVIDEO)
);