drop database if exists exercicio17;

create database exercicio17;


use exercicio17;

CREATE TABLE ESCOLA (
IDESCOLA INT NOT NULL,
NOME_ESCOLA VARCHAR(100),
RUA VARCHAR (150),
CEP CHAR (8),
NUMERO INT,
PRIMARY KEY (IDESCOLA)
);
CREATE TABLE ALUNO (
IDALUNO INT NOT NULL,
IDESCOLA INT,
NOME VARCHAR (100),
NOME_PAI VARCHAR (100),
NOME_MAE VARCHAR (100),
DATA_DE_NASCIMENTO DATE,
PRIMARY KEY (IDALUNO),
FOREIGN KEY (IDESCOLA) REFERENCES ESCOLA (IDESCOLA)
);