-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS DBEXERCICIO23;

-- CRIANDO A BASE DE DADOS 
CREATE DATABASE DBEXERCICIO23;
	
-- CONECTANDO NA BASE DE DADOS
USE DBEXERCICIO23;
-- CRIANDO AS TABELAS

CREATE TABLE NIVEL (
IDNIVEL INT NOT NULL,
NOME VARCHAR (100),
VALOR DECIMAL(8,2),
PRIMARY KEY (IDNIVEL)
);

CREATE TABLE PARTICIPANTE (
IDPARTICIPANTE INT NOT NULL,
NOME VARCHAR (100),
FONE INT,
EMAIL varchar(100),
PRIMARY KEY (IDPARTICIPANTE)
);

CREATE TABLE OFICINA (
IDOFICINA INT NOT NULL,
NOME VARCHAR (100),
ASSUNTO VARCHAR (100),
IDNIVEL INT,
PRIMARY KEY (IDOFICINA),
FOREIGN KEY (IDNIVEL) REFERENCES NIVEL (IDNIVEL)
);

CREATE TABLE INSCRICAO (
IDINSCRICAO INT NOT NULL,
IDOFICINA INT NOT NULL,
HORA DATETIME,
DATA_INSCRICAO DATE,
PRIMARY KEY (IDINSCRICAO),
FOREIGN KEY (IDOFICINA) REFERENCES OFICINA (IDOFICINA)
);


