DROP DATABASE IF EXISTS DBEXERCICIO07;
CREATE DATABASE DBEXERCICIO07;
USE DBEXERCICIO07;
CREATE TABLE ALUNO(
	IDALUNO INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(100),
	DATA_DE_NASCIMENTO INT,
    TELEFONE_CEL_DDD CHAR(10),
    TELEFONE_CEL_DDD CHAR(11),
    TELEFONE_CONTATO_DDD varchar(200),
	PRIMARY KEY (IDALUNO)
);