DROP DATABASE IF EXISTS EXERCICIO21;
CREATE DATABASE EXERCICIO21;

USE EXERCICIO21;

CREATE TABLE VITIMA(
IDVITIMA INT NOT NULL auto_increment,
NOME VARCHAR (100),
DTNASCIMENTO date,
PRIMARY KEY (IDVITIMA)
);

CREATE TABLE CRIMINOSO(
IDCRIMINOSO INT NOT NULL auto_increment,
NOME VARCHAR (100),
DTNASCIMENTO date,
PRIMARY KEY (IDCRIMINOSO)
);


CREATE TABLE CRIME(
IDCRIME INT NOT NULL auto_increment,
DESCRICAO VARCHAR (100),
DTCRIME date,
PRIMARY KEY (IDCRIME)
);


CREATE TABLE ARMA(
IDARMA INT NOT NULL auto_increment,
TIPO VARCHAR (100),
NUMERO_IDENTIFICADOR INT,
PRIMARY KEY (IDARMA)
);

CREATE TABLE ATACAR (
IDCRIMINOSO INT NOT NULL,
IDVITIMA INT NOT NULL,
primary key (IDCRIMINOSO, IDVITIMA),
FOREIGN KEY (IDCRIMINOSO) REFERENCES CRIMINOSO (IDCRIMINOSO),
FOREIGN KEY (IDVITIMA) REFERENCES VITIMA (IDVITIMA)
);

CREATE TABLE SOFRER (
IDVITIMA INT NOT NULL,
IDCRIME INT NOT NULL,
primary key (IDVITIMA, IDCRIME),
FOREIGN KEY (IDVITIMA) REFERENCES VITIMA (IDVITIMA),
FOREIGN KEY (IDCRIME) REFERENCES CRIME (IDCRIME)
);

CREATE TABLE COMETER (
IDCRIME INT NOT NULL,
IDCRIMINOSO INT NOT NULL,
primary key (IDCRIME, IDCRIMINOSO),
FOREIGN KEY (IDCRIME) REFERENCES CRIME (IDCRIME),
FOREIGN KEY (IDCRIMINOSO) REFERENCES CRIMINOSO (IDCRIMINOSO)
);

CREATE TABLE USAR (
IDCRIME INT NOT NULL,
IDARMA INT NOT NULL,
primary key (IDCRIME, IDARMA),
FOREIGN KEY (IDCRIME) REFERENCES CRIME (IDCRIME),
FOREIGN KEY (IDARMA) REFERENCES ARMA (IDARMA)
);





