drop database if exists exercicio19;
create database exercicio19;
use exercicio19;

CREATE TABLE PESSOA_FISICA_JURIDICA (
IDPESSOA INT NOT NULL,
TELEFONE INT,
NOME VARCHAR (100),
CPF CHAR(11),
CNPJ CHAR (14),
PRIMARY KEY (IDPESSOA)
);
CREATE TABLE PEDIDO (
IDPEDIDO INT NOT NULL,
IDPESSOA INT,
DTPEDIDO DATE,
PRIMARY KEY (IDPEDIDO),
FOREIGN KEY (IDPESSOA) REFERENCES PESSOA_FISICA_JURIDICA (IDPESSOA)
);