DROP DATABASE IF EXISTS DBEXERCICIO06;
CREATE DATABASE DBEXERCICIO06;
USE DBEXERCICIO06;
CREATE TABLE ALUNO (
	IDALUNO INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(100),
	IDADE INT,
    RUA VARCHAR(100),
    NUMERO INT,
    BAIRRO VARCHAR(100),
    CIDADE varchar(100),
    ESTADO VARCHAR (100),
    CEP varchar(8),
    COMPLEMENTO VARCHAR(100),
	PRIMARY KEY (IDALUNO)
);