DROP DATABASE IF EXISTS exercicio13;
CREATE DATABASE exercicio13;
USE exercicio13;

-- CRIANDO AS TABELAS
CREATE TABLE PEDIDO (
	IDPEDIDO INT NOT NULL AUTO_INCREMENT
    , DTPEDIDO DATE
    , HRPEDIDO TIME
    , CLIENTE VARCHAR(45)
    , PRIMARY KEY (IDPEDIDO)
);

CREATE TABLE PRODUTO (
	IDPRODUTO INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(45)
    , VALOR DECIMAL(8,2)
    , PRIMARY KEY (IDPRODUTO)
);

CREATE TABLE COMPRAR (
	IDPEDIDO INT NOT NULL
    , IDPRODUTO INT NOT NULL
    , PRIMARY KEY (IDPEDIDO, IDPRODUTO)
    , FOREIGN KEY (IDPEDIDO) REFERENCES PEDIDO(IDPEDIDO)
    , FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO(IDPRODUTO)
);