DROP DATABASE IF EXISTS DBEXERCICIO04;
CREATE DATABASE DBEXERCICIO04;
USE DBEXERCICIO04;
CREATE TABLE OBRA (
	IDOBRA INT NOT NULL AUTO_INCREMENT,
	IDUSUARIO VARCHAR(100),
	IMAGEM VARCHAR(100),
    ENDERECO VARCHAR(100),
    DESCRICAO varchar(500),
    DATA_INICIAL INT,
	DATA_FINAL INT,
	PRIMARY KEY (IDOBRA)
);
CREATE TABLE DENUNCIA (
	IDDENUNCIA INT NOT NULL AUTO_INCREMENT,
	IDUSUARIO VARCHAR(100),
	IMAGEM VARCHAR(100),
    ENDERECO VARCHAR(100),
    DESCRICAO varchar(500),
    DATA_DENUNCIA INT,
	PRIMARY KEY (IDDENUNCIA)
);
CREATE TABLE USUARIO (
	IDUSUARIO INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(100),
    E_MAIL VARCHAR(100),
    SENHA VARCHAR(45),
	DATA_DE_NASCIMENTO INT,
	PRIMARY KEY (IDUSUARIO)
);