CREATE TABLE VEICULO_RENAVAM (
ID_VEICULO INT NOT NULL,
ID_RENAVAM INT NOT NULL,
ANO_DE_FABRICACAO INT,
MARCA VARCHAR (45),
PLACA_DO_VEICULO CHAR(7),
MODELO VARCHAR(30),
CIDADE VARCHAR (45),
DATA_DE_REGISTRO INT,
ESTADO CHAR(2),
PRIMARY KEY (ID_VEICULO, ID_RENAVAM)
);