
drop database if exists exercicio17;


create database exercicio17;


use exercicio17;


CREATE TABLE MERCADO (
IDMERCADO INT NOT NULL,
ENDEREÇO VARCHAR(150),
NOME VARCHAR(100),
PRIMARY KEY (IDMERCADO)
);
CREATE TABLE PRODUTO (
IDPRODUTO INT NOT NULL,
IDMERCADO INT,
TIPO_PRODUTO VARCHAR(100),
VALIDADE INT,
NOME VARCHAR(100),
PRIMARY KEY (IDPRODUTO),
FOREIGN KEY (IDMERCADO) REFERENCES MERCADO (IDMERCADO)
);

