const produtos = [
    {nome: "bicicleta1", preco: 200.40, validade: true},
    {nome: "cama box", preco: 500.00, validade: true},
    {nome: "televisão", preco: 1100.00, validade: true},
    {nome: "Agua de coco", preco: 50.00, validade: false},
    {nome: "chocolate meio amargo", preco: 3.89, validade: false},
    {nome: "pilha", preco: 150.00, validade: true},
    {nome: "Kinder ovo", preco: 100.00, validade: false},
    {nome: "pc gamer", preco: 10000.00, validade: true},
    {nome: "janela", preco: 300.00, validade: true},
    {nome: "mochila", preco: 120.30, validade: true},
    {nome: "pasta de dente", preco: 6.00, validade: false},
    {nome: "cadeira", preco: 432.00, validade: true},
    {nome: "projetor", preco: 2200.00, validade: true},
    {nome: "banana obras", preco: 10500.00, validade: false},
    {nome: "oculos de sol", preco: 20.00, validade: true},
    {nome: "teclado", preco: 700.00, validade: true},
    {nome: "mouse", preco: 500.00, validade: false},
    {nome: "pen drive", preco: 5.00, validade: true},
    {nome: "garrafa twpperware", preco: 370.80, validade: false},
    {nome: "bassit", preco: 30000.00, validade: false},
    {nome: "filtro de barro", preco: 83.12, validade: true},
    {nome: "cama box2", preco: 67.56,validade: true},
    {nome: "cama box3", preco: 78.11, validade: true},
    {nome: "cama box4", preco: 2345.67, validade: false},
    {nome: "cama box5", preco: 764.56, validade: true},
    {nome: "cama box6", preco: 999.66, validade: false},
    {nome: "cama box7", preco: 580.30, validade: true},
    {nome: "cama box8", preco: 1222.00, validade: false},
    {nome: "cama box9", preco: 48.00, validade: true},
    {nome: "cama box10", preco: 50.00, validade: true},
]
console.log("Todas os produtos", produtos);
console.log("produtos a venda ", produtos.filter(b=> b.validade));
console.log("produtos entre 50 e 100 reais ", produtos.filter(prod=> prod.preco >=50 && prod.preco <=100));