drop database if exists exercicio18;
create database exercicio18;
use exercicio18;

CREATE TABLE DEPARTAMENTO(
	IDDEPARTAMENTO INT NOT NULL AUTO_INCREMENT,
	NOME_DEPARTAMENTO VARCHAR(100) NOT NULL,
    PRIMARY KEY (IDDEPARTAMENTO)
 );
CREATE TABLE FUNCIONARIO(
	IDFUNCIONARIO INT NOT NULL AUTO_INCREMENT,
    IDDEPARTAMENTO INT,
    NOME_DEPARTAMENTO VARCHAR(100),
    NOME_FUNCIONARIO VARCHAR(100) NOT NULL,
    DATA_ADMISSAO DATE,
    TELEFONE INT NOT NULL,
    PRIMARY KEY (IDFUNCIONARIO),
	FOREIGN KEY(IDDEPARTAMENTO) REFERENCES DEPARTAMENTO(IDDEPARTAMENTO)
);