DROP DATABASE IF EXISTS DBEXERCICIO09;
CREATE DATABASE DBEXERCICIO09;
USE DBEXERCICIO09;
CREATE TABLE CANDIDATO (
	IDCANDIDATO INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(45),
	EMAIL varchar(45),
    SEXO CHAR(1),
    SENHA VARCHAR (45),
    FONE_1 VARCHAR(15),
    FONE_2 VARCHAR (15),
    FONE_3 VARCHAR (15),
	PRIMARY KEY (IDCANDIDATO)
);