drop database if exists exercicio16;
create database exercicio16;
use exercicio16;

CREATE TABLE TITULAR (
IDTITULAR INT NOT NULL,
NOME VARCHAR (100),
CPF CHAR(11),
PRIMARY KEY (IDTITULAR)
);
CREATE TABLE DEPENDENTE (
IDDEPENDENTE INT NOT NULL,
IDTITULAR INT,
NOME VARCHAR (100),
NASCIMENTO DATE,
PRIMARY KEY (IDDEPENDENTE),
FOREIGN KEY (IDTITULAR) REFERENCES TITULAR (IDTITULAR)
);