DROP DATABASE IF EXISTS DBEXERCICIO08;
CREATE DATABASE DBEXERCICIO08;
USE DBEXERCICIO08;
CREATE TABLE ELEITOR (
	IDELEITOR INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(100),
	EMAIL varchar(100),
    CIDADE VARCHAR(100),
    ESTADO VARCHAR(100),
    SEXO CHAR(1),
    ANIVERSARIO date,
    TELEFONE1 INT,
    TELEFONE2 INT,
    TELEFONE3 INT,
    ENDERECO_COMPLETO VARCHAR(150),
    CEP INT,
	PRIMARY KEY (IDELEITOR)
);